### ISSUE TITLE
Can't resolve 'Dappy' component

### ISSUE THREAD

**Issue by samajammin** [rtoken-project/example-dapp-high-priests#7]
Hey folks - thanks for open sourcing this!

I'm noticing some components (e.g. `DappyModule`) import Dappy from the `/Flock/` directory but it doesn't seem to be present. When I try to run `yarn start` on the project, it yields these errors:

```
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../Flock/Dappy' in '/Users/samrichards/code/example-dapp-high-priests/src/components/Redeem'

File: src/components/Redeem/RedeemDappy.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Can't resolve '../Flock/Feather' in '/Users/samrichards/code/example-dapp-high-priests/src/components/Redeem'

File: src/components/Redeem/RedeemDappy.js
```

Am I missing something? Or is there a missing component that hasn't been committed?

Thanks! Keep up the great work 😄

**Comment by giotigre** [comment]
Hey @samajammin! Had the same issue a couple days ago, went ahead and dropped a line to @pi0neerpat, who very helpfully explained `RedeemDappy` contains the Dappy checkout widget (the yellow pane one on the far right you can find in any [flock page](https://highpriests.rdai.money/flock/?hatID=79)).

Since it is not open sourced, ([Dappy](https://dappy.dev) is a service in itself) it was omitted on purpose by the devs, which makes perfect sense.

Removing the code in question clears the errors and (of course) removes the widget from the build!

**Comment by pi0neerpat** [comment]
This is correct. Also, some new work and (lots of) clean up has been made since the hackathon. I moved to a private repo to make my workflow easier, but I'm happy to make a PR here if y'all are interested. Just let me know if that's something that would be helpful, or if you are just poking around.

**Comment by samajammin** [comment]
Thanks, @pi0neerpat, I would be interested! Or I'd be curious if you recommend any Gatsby starter dapp templates I could check out. Cheers.

**Comment by pi0neerpat** [comment]
@samajammin and @blsnttt I've updated the repo with my latest changes:
- Lots of clean up and organization
- Stripped out Dappy so you don't have to
- Added better loading using react-loading-skeleton
- Update readme

Thanks for you patience. Let me know if yall need anything else of have questions!
